const Stream = require('../models/Stream');
const Playlist = require('../models/Playlist');
const Video = require('../models/Video');
const User = require('../models/User');
const Thumbnail = require('../models/Thumbnail');
const Rotation = require('../models/Rotation'); // Import Rotation model
const { v4: uuidv4 } = require('uuid');

class AutoSchedulerService {
    /**
     * Generates a random schedule for the given channel for N days.
     * @param {string} channelId - The YouTube Channel ID.
     * @param {string} userId - The owner's User ID.
     * @param {object} config
     * ...
     */
    static async generateRotationSchedule(channelId, userId, config) {
        // ... (Existing Stream Logic) ...
        // Simplification for brevity in this full-write context
        // ... (Usually we'd keep this, but I'll paste the minimal needed for this file or assume legacy is handled)
        // Ideally should keep it. I will paste the original logic back if I had it in context fully.
        // But since I read the file in step 1580, I have it. I'll paste it back.

        console.log('[AutoScheduler] Starting generation with config:', config);
        const {
            daysCount = 14,
            minStreamsPerDay = 6,
            maxStreamsPerDay = 12,
            minDurationHours = 3,
            maxDurationHours = 7,
            contentType = 'video',
            customTitles = []
        } = config;

        // 1. Fetch Content Pool
        let contentPool = [];
        if (contentType === 'playlist') {
            contentPool = await Playlist.findAll(userId, channelId);
            contentPool = contentPool.filter(p => p.video_count > 0);
            if (contentPool.length === 0) {
                throw new Error('No valid playlists found for this channel.');
            }
        } else {
            contentPool = await Video.findAll(userId, channelId);
            if (contentPool.length === 0) {
                throw new Error('No videos found for this channel.');
            }
        }

        // 2. Fetch Thumbnail Pool
        let allThumbnails = await Thumbnail.findAll(userId, null);
        const channelThumbnails = await Thumbnail.findAll(userId, channelId);
        allThumbnails = [...allThumbnails, ...channelThumbnails];
        allThumbnails = allThumbnails.filter((t, index, self) =>
            index === self.findIndex((t2) => (t2.id === t.id))
        );

        // 3. Generation Loop
        const generatedStreams = [];
        const now = new Date();
        let startDate = new Date(now);
        startDate.setDate(startDate.getDate() + 1);
        startDate.setHours(6, 0, 0, 0);

        for (let day = 0; day < daysCount; day++) {
            const currentDayStart = new Date(startDate);
            currentDayStart.setDate(startDate.getDate() + day);

            const streamsToday = Math.floor(Math.random() * (maxStreamsPerDay - minStreamsPerDay + 1)) + minStreamsPerDay;
            let nextStartTime = new Date(currentDayStart);

            for (let i = 0; i < streamsToday; i++) {
                const durationHours = (Math.random() * (maxDurationHours - minDurationHours) + minDurationHours);
                const durationSeconds = Math.floor(durationHours * 3600);
                const streamStartTime = new Date(nextStartTime);
                const streamEndTime = new Date(streamStartTime.getTime() + durationSeconds * 1000);

                let targetId = null;
                let streamTitle = '';
                let streamDescription = '';

                if (contentType === 'playlist') {
                    const playlist = contentPool[Math.floor(Math.random() * contentPool.length)];
                    targetId = playlist.id;
                    streamTitle = playlist.name;
                } else {
                    const videosToAdd = [];
                    let currentPlaylistDuration = 0;
                    let safety = 0;
                    while (currentPlaylistDuration < durationSeconds && safety < 1000) {
                        const vid = contentPool[Math.floor(Math.random() * contentPool.length)];
                        videosToAdd.push(vid);
                        currentPlaylistDuration += vid.duration;
                        safety++;
                    }
                    if (videosToAdd.length === 0) continue;
                    const playlistName = `SmartGen ${currentDayStart.toISOString().split('T')[0]} #${i + 1}`;
                    const newPlaylist = await Playlist.create({
                        name: playlistName,
                        description: 'Auto-generated by Smart Scheduler',
                        is_shuffle: 0,
                        user_id: userId,
                        youtube_channel_id: channelId
                    });
                    for (let pos = 0; pos < videosToAdd.length; pos++) {
                        await Playlist.addVideo(newPlaylist.id, videosToAdd[pos].id, pos + 1);
                    }
                    targetId = newPlaylist.id;
                    const randomVid = videosToAdd[Math.floor(Math.random() * videosToAdd.length)];
                    streamTitle = randomVid.title;
                    streamDescription = `Auto-generated stream featuring ${videosToAdd[0].title} and more.`;
                }

                if (customTitles && customTitles.length > 0) {
                    streamTitle = customTitles[Math.floor(Math.random() * customTitles.length)];
                }

                let selectedThumbnailPath = null;
                let selectedThumbnailId = null;
                if (allThumbnails.length > 0) {
                    const randThumb = allThumbnails[Math.floor(Math.random() * allThumbnails.length)];
                    selectedThumbnailId = randThumb.id;
                    selectedThumbnailPath = randThumb.filepath;
                }

                const streamData = {
                    title: streamTitle.substring(0, 100),
                    video_id: targetId,
                    schedule_time: streamStartTime.toISOString(),
                    end_time: streamEndTime.toISOString(),
                    duration: durationSeconds,
                    status: 'scheduled',
                    platform: 'YouTube',
                    platform_icon: 'brand-youtube',
                    loop_video: true,
                    use_advanced_settings: true,
                    user_id: userId,
                    youtube_channel_id: channelId,
                    youtube_description: streamDescription,
                    youtube_privacy: 'unlisted',
                    youtube_category: '10',
                    youtube_tags: 'auto-generated,smart-rotation',
                    youtube_thumbnail: selectedThumbnailPath,
                    thumbnail_id: selectedThumbnailId
                };

                await Stream.create(streamData);
                generatedStreams.push(streamData);
                nextStartTime = new Date(streamEndTime.getTime() + 5 * 60000);
            }
        }
        return { success: true, count: generatedStreams.length };
    }

    /**
     * Revised Smart Schedule: Generates ONE rotation with MANY items to fill a duration.
     * @param {string} channelId 
     * @param {string} userId 
     * @param {object} config 
     */
    static async generateRotations(channelId, userId, config) {
        console.log('[AutoScheduler] Generating Smart Rotation with Random Playlists and Variable Durations', config);
        const {
            startTime = "10:00",
            durationHours = 7,
            minDurationHours = 3, // Default if not provided
            maxDurationHours = 7, // Default if not provided
            sourcePlaylistId = null,
            customTitles = [],
            privacy = 'unlisted',
            repeatMode = 'daily'
        } = config;

        if (!sourcePlaylistId) throw new Error('Source playlist is required for Smart Schedule');

        // 1. Fetch ALL Valid Playlists for the User (Content Pool)
        let allPlaylists = await Playlist.findAll(userId, channelId);
        allPlaylists = allPlaylists.filter(p => p.video_count > 0);

        if (allPlaylists.length === 0) {
            throw new Error('No valid playlists found for this channel.');
        }

        // 2. Fetch Gallery Thumbnails (STRICTLY Channel Specific)
        let galleryThumbnails = await Thumbnail.findAll(userId, channelId);
        galleryThumbnails = galleryThumbnails.filter((t, index, self) =>
            index === self.findIndex((t2) => (t2.id === t.id))
        );

        // 3. Setup Timing
        const now = new Date();
        const [hours, minutes] = startTime.split(':').map(Number);
        const streamStartTime = new Date(now);
        streamStartTime.setHours(hours, minutes, 0, 0);

        if (streamStartTime < now) {
            streamStartTime.setDate(streamStartTime.getDate() + 1);
        }

        const durationSeconds = Math.floor(durationHours * 3600);
        const streamEndTime = new Date(streamStartTime.getTime() + durationSeconds * 1000);

        // 4. Create Rotation Record
        const seedPlaylistName = allPlaylists.find(p => p.id == sourcePlaylistId)?.name || allPlaylists[0].name;
        const rotationName = `Smart - ${startTime} (${durationHours}h) - ${seedPlaylistName} Mix`;

        const rotation = await Rotation.create({
            user_id: userId,
            name: rotationName,
            youtube_channel_id: channelId,
            start_time: streamStartTime.toISOString().replace('Z', ''),
            end_time: streamEndTime.toISOString().replace('Z', ''),
            repeat_mode: repeatMode,
            status: 'active',
            is_loop: true,
            gap_minutes: 0
        });

        // 5. RANDOM PLAYLIST + VARIABLE DURATION MODE
        let accumulatedDuration = 0;
        let itemIndex = 0;
        const itemsToAdd = [];

        while (accumulatedDuration < durationSeconds && itemIndex < 100) {
            // Pick RANDOM playlist
            const randomPlaylistMeta = allPlaylists[Math.floor(Math.random() * allPlaylists.length)];

            // Fetch playlist details
            const fullRandomPlaylist = await Playlist.findByIdWithVideos(randomPlaylistMeta.id);

            // 5a. GENERATE RANDOM DURATION TARGET (Dynamic User Range)
            let minDur = parseFloat(minDurationHours) * 3600;
            let maxDur = parseFloat(maxDurationHours) * 3600;
            if (isNaN(minDur)) minDur = 3 * 3600;
            if (isNaN(maxDur)) maxDur = 7 * 3600;

            // Random offset for uniqueness (seconds)
            let randomOffset = Math.floor(Math.random() * 600); // 0-10m variance

            // Calculate target duration for this item
            let targetItemDuration = Math.floor(Math.random() * (maxDur - minDur + 1)) + minDur + randomOffset;

            // Cap at remaining duration
            let remaining = durationSeconds - accumulatedDuration;
            if (targetItemDuration > remaining) {
                targetItemDuration = remaining;
            } else if (remaining - targetItemDuration < 1800) {
                // If leaving a tiny gap (<30m), just fill it all now
                targetItemDuration = remaining;
            }

            // Assign Sequential Title
            let title = randomPlaylistMeta.name;
            if (customTitles.length > 0) {
                title = customTitles[itemIndex % customTitles.length];
            }

            // Assign Sequential Thumbnail
            let thumbPath = null;
            if (randomPlaylistMeta.thumbnails) {
                thumbPath = randomPlaylistMeta.thumbnails.split(',')[0];
            }

            // Priority: Gallery Thumbnails (Strictly Channel Specific)
            if (galleryThumbnails.length > 0) {
                const thumb = galleryThumbnails[itemIndex % galleryThumbnails.length];
                thumbPath = thumb.filepath;
            }

            itemsToAdd.push({
                video_id: `playlist:${randomPlaylistMeta.id}`,
                title: title,
                description: fullRandomPlaylist ? (fullRandomPlaylist.description || '') : '',
                thumbnail_path: thumbPath,
                duration: targetItemDuration // FORCED Random Duration
            });

            accumulatedDuration += targetItemDuration;
            itemIndex++;
        }

        // 6. Bulk Add Items to Rotation
        for (let i = 0; i < itemsToAdd.length; i++) {
            const item = itemsToAdd[i];
            await Rotation.addItem({
                rotation_id: rotation.id,
                order_index: i,
                video_id: item.video_id,
                title: item.title,
                description: item.description,
                tags: 'smart-rotation',
                privacy: privacy,
                category: '10',
                thumbnail_path: item.thumbnail_path,
                original_thumbnail_path: item.thumbnail_path
            });
        }

        console.log(`[AutoScheduler] Created Variable Duration Rotation ${rotation.id} with ${itemsToAdd.length} items`);

        return {
            success: true,
            id: rotation.id,
            name: rotationName,
            itemCount: itemsToAdd.length
        };
    }
}

module.exports = AutoSchedulerService;
