const Stream = require('../models/Stream');
const Playlist = require('../models/Playlist');
const Video = require('../models/Video');
const User = require('../models/User');
const Thumbnail = require('../models/Thumbnail');
const Rotation = require('../models/Rotation'); // Import Rotation model
const { v4: uuidv4 } = require('uuid');

class AutoSchedulerService {
    /**
     * Generates a random schedule for the given channel for N days.
     * @param {string} channelId - The YouTube Channel ID.
     * @param {string} userId - The owner's User ID.
     * @param {object} config - Configuration object.
     * @param {number} config.daysCount - Number of days to generate.
     * @param {number} config.minStreamsPerDay - Min streams per day.
     * @param {number} config.maxStreamsPerDay - Max streams per day.
     * @param {number} config.minDurationHours - Min duration per stream.
     * @param {number} config.maxDurationHours - Max duration per stream.
     * @param {string} config.contentType - 'video' or 'playlist'.
     * @param {string[]} config.customTitles - Array of custom titles to randomize.
     */
    static async generateRotationSchedule(channelId, userId, config) {
        // ... (Existing Stream Logic - kept for reference or legacy use) ...
        // For brevity in this edit, I will focus on adding the new method below.
        // But since I'm rewriting the file, I should include the existing method too.
        console.log('[AutoScheduler] Starting generation with config:', config);
        const {
            daysCount = 14,
            minStreamsPerDay = 6,
            maxStreamsPerDay = 12,
            minDurationHours = 3,
            maxDurationHours = 7,
            contentType = 'video',
            customTitles = []
        } = config;

        // 1. Fetch Content Pool
        let contentPool = [];
        if (contentType === 'playlist') {
            contentPool = await Playlist.findAll(userId, channelId);
            contentPool = contentPool.filter(p => p.video_count > 0);
            if (contentPool.length === 0) {
                throw new Error('No valid playlists found for this channel.');
            }
        } else {
            contentPool = await Video.findAll(userId, channelId);
            if (contentPool.length === 0) {
                throw new Error('No videos found for this channel.');
            }
        }

        // 2. Fetch Thumbnail Pool
        let allThumbnails = await Thumbnail.findAll(userId, null);
        const channelThumbnails = await Thumbnail.findAll(userId, channelId);
        allThumbnails = [...allThumbnails, ...channelThumbnails];
        allThumbnails = allThumbnails.filter((t, index, self) =>
            index === self.findIndex((t2) => (t2.id === t.id))
        );

        // 3. Generation Loop
        const generatedStreams = [];
        const now = new Date();
        let startDate = new Date(now);
        startDate.setDate(startDate.getDate() + 1);
        startDate.setHours(6, 0, 0, 0);

        for (let day = 0; day < daysCount; day++) {
            const currentDayStart = new Date(startDate);
            currentDayStart.setDate(startDate.getDate() + day);

            const streamsToday = Math.floor(Math.random() * (maxStreamsPerDay - minStreamsPerDay + 1)) + minStreamsPerDay;
            let nextStartTime = new Date(currentDayStart);

            for (let i = 0; i < streamsToday; i++) {
                const durationHours = (Math.random() * (maxDurationHours - minDurationHours) + minDurationHours);
                const durationSeconds = Math.floor(durationHours * 3600);
                const streamStartTime = new Date(nextStartTime);
                const streamEndTime = new Date(streamStartTime.getTime() + durationSeconds * 1000);

                let targetId = null;
                let streamTitle = '';
                let streamDescription = '';

                if (contentType === 'playlist') {
                    const playlist = contentPool[Math.floor(Math.random() * contentPool.length)];
                    targetId = playlist.id;
                    streamTitle = playlist.name;
                } else {
                    const videosToAdd = [];
                    let currentPlaylistDuration = 0;
                    let safety = 0;
                    while (currentPlaylistDuration < durationSeconds && safety < 1000) {
                        const vid = contentPool[Math.floor(Math.random() * contentPool.length)];
                        videosToAdd.push(vid);
                        currentPlaylistDuration += vid.duration;
                        safety++;
                    }
                    if (videosToAdd.length === 0) continue;
                    const playlistName = `SmartGen ${currentDayStart.toISOString().split('T')[0]} #${i + 1}`;
                    const newPlaylist = await Playlist.create({
                        name: playlistName,
                        description: 'Auto-generated by Smart Scheduler',
                        is_shuffle: 0,
                        user_id: userId,
                        youtube_channel_id: channelId
                    });
                    for (let pos = 0; pos < videosToAdd.length; pos++) {
                        await Playlist.addVideo(newPlaylist.id, videosToAdd[pos].id, pos + 1);
                    }
                    targetId = newPlaylist.id;
                    const randomVid = videosToAdd[Math.floor(Math.random() * videosToAdd.length)];
                    streamTitle = randomVid.title;
                    streamDescription = `Auto-generated stream featuring ${videosToAdd[0].title} and more.`;
                }

                if (customTitles && customTitles.length > 0) {
                    streamTitle = customTitles[Math.floor(Math.random() * customTitles.length)];
                }

                let selectedThumbnailPath = null;
                let selectedThumbnailId = null;
                if (allThumbnails.length > 0) {
                    const randThumb = allThumbnails[Math.floor(Math.random() * allThumbnails.length)];
                    selectedThumbnailId = randThumb.id;
                    selectedThumbnailPath = randThumb.filepath;
                }

                const streamData = {
                    title: streamTitle.substring(0, 100),
                    video_id: targetId,
                    schedule_time: streamStartTime.toISOString(),
                    end_time: streamEndTime.toISOString(),
                    duration: durationSeconds,
                    status: 'scheduled',
                    platform: 'YouTube',
                    platform_icon: 'brand-youtube',
                    loop_video: true,
                    use_advanced_settings: true,
                    user_id: userId,
                    youtube_channel_id: channelId,
                    youtube_description: streamDescription,
                    youtube_privacy: 'unlisted',
                    youtube_category: '10',
                    youtube_tags: 'auto-generated,smart-rotation',
                    youtube_thumbnail: selectedThumbnailPath,
                    thumbnail_id: selectedThumbnailId
                };

                await Stream.create(streamData);
                generatedStreams.push(streamData);
                nextStartTime = new Date(streamEndTime.getTime() + 5 * 60000);
            }
        }
        return { success: true, count: generatedStreams.length };
    }

    /**
     * Generates ROTATION records instead of Stream records.
     * This allows them to appear in the "Rotations" UI with full features.
     */
    static async generateRotations(channelId, userId, config) {
        console.log('[AutoScheduler] Starting ROTATION generation with config:', config);
        const {
            daysCount = 14,
            minStreamsPerDay = 6,
            maxStreamsPerDay = 12,
            minDurationHours = 3,
            maxDurationHours = 8,
            contentType = 'video',
            sourcePlaylistId = null,
            customTitles = [],
            privacy = 'unlisted',
            repeatMode = 'none',
            thumbnailMode = 'auto' // auto | gallery | video
        } = config;

        // 1. Fetch Content Pool
        let contentPool = [];
        if (sourcePlaylistId) {
            // Source from Specific Playlist
            const playlist = await Playlist.findByIdWithVideos(sourcePlaylistId);
            if (!playlist) throw new Error('Source playlist not found');

            // Filter out audio-only if needed, or keep them if mixed.
            // For streams, we usually want videos.
            contentPool = playlist.videos || [];

            // Filter out missing files if possible?
            // Assuming playlist.videos have full video objects. 
            // The query returns `v.*`, so yes.
        } else if (contentType === 'playlist') {
            // Fallback to old behavior: Random Playlist Selection
            // (We might not use this via the new UI, but keeping for compatibility)
            contentPool = await Playlist.findAll(userId, channelId);
            contentPool = contentPool.filter(p => p.video_count > 0);
        } else {
            // All Videos
            contentPool = await Video.findAll(userId, channelId);
            // Filter out audio
            contentPool = contentPool.filter(v =>
                !v.filepath.includes('/audio/') &&
                !v.filepath.endsWith('.mp3') &&
                !v.filepath.endsWith('.m4a') &&
                !v.filepath.endsWith('.aac')
            );
        }

        if (contentPool.length === 0) {
            throw new Error(`No valid content found for the selected source.`);
        }

        // 2. Fetch Thumbnail Pool (Gallery)
        let galleryThumbnails = [];
        if (thumbnailMode !== 'video') {
            galleryThumbnails = await Thumbnail.findAll(userId, null);
            const channelThumbnails = await Thumbnail.findAll(userId, channelId);
            galleryThumbnails = [...galleryThumbnails, ...channelThumbnails];
            galleryThumbnails = galleryThumbnails.filter((t, index, self) =>
                index === self.findIndex((t2) => (t2.id === t.id))
            );
        }

        // 3. Generation Loop
        const generatedCount = [];
        const now = new Date();
        let startDate = new Date(now);
        startDate.setDate(startDate.getDate() + 1);
        startDate.setHours(6, 0, 0, 0);

        for (let day = 0; day < daysCount; day++) {
            const currentDayStart = new Date(startDate);
            currentDayStart.setDate(startDate.getDate() + day);

            const streamsToday = Math.floor(Math.random() * (maxStreamsPerDay - minStreamsPerDay + 1)) + minStreamsPerDay;
            let nextStartTime = new Date(currentDayStart);

            for (let i = 0; i < streamsToday; i++) {
                const durationHours = (Math.random() * (maxDurationHours - minDurationHours) + minDurationHours);
                const durationSeconds = Math.floor(durationHours * 3600);

                const streamStartTime = new Date(nextStartTime);
                const streamEndTime = new Date(streamStartTime.getTime() + durationSeconds * 1000);

                let rotationName = `Smart - ${streamStartTime.toLocaleDateString('id-ID', { day: '2-digit', month: 'short' })} ${streamStartTime.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit', hour12: false })}`;

                let displayTitle = '';
                if (customTitles && customTitles.length > 0) {
                    displayTitle = customTitles[Math.floor(Math.random() * customTitles.length)];
                }

                // Create Rotation Record
                const rotation = await Rotation.create({
                    user_id: userId,
                    name: rotationName,
                    youtube_channel_id: channelId,
                    start_time: streamStartTime.toISOString().replace('Z', ''),
                    end_time: streamEndTime.toISOString().replace('Z', ''),
                    repeat_mode: repeatMode,
                    status: 'active',
                    is_loop: true,
                    gap_minutes: 0
                });

                // Pick Content
                let targetId = '';
                let targetTitle = '';
                let targetDesc = '';
                let contentThumbnailFallback = null;

                if (contentType === 'playlist' && !sourcePlaylistId) {
                    // Legacy: Pick a random playlist as the content
                    const pl = contentPool[Math.floor(Math.random() * contentPool.length)];
                    targetId = `playlist:${pl.id}`;
                    targetTitle = pl.name;
                    targetDesc = pl.description || '';
                    if (pl.thumbnails) {
                        contentThumbnailFallback = pl.thumbnails.split(',')[0];
                    }
                } else {
                    // Video Source (Either from 'sourcePlaylistId' videos OR 'All Videos')
                    // We need to pick enough videos to fill the duration?
                    // User request: "video dari playlist" (videos from playlist).
                    // If we pick just ONE video, it might loop.
                    // If we want a "Rotation Item" to be a playlist of videos, we need to create a TEMP playlist or use single video.
                    // Rotations support single video or playlist ID.

                    // Strategy: Pick 1 random video from the pool and loop it (simple),
                    // OR pick a random subset and create a TEMP playlist?
                    // "Item ... video berbeda lagi" => Different videos for each rotation item.
                    // If I pick 1 video, it will loop for 3-8 hours.
                    // If I pick multiple, I need to create a playlist.

                    // Let's create a temp playlist to be safe and ensure variety if pool is large.

                    const videosToAdd = [];
                    let currentPlaylistDuration = 0;
                    let safety = 0;

                    // Shuffle pool snippet
                    const poolCopy = [...contentPool];

                    while (currentPlaylistDuration < durationSeconds && safety < 100 && poolCopy.length > 0) {
                        const randIdx = Math.floor(Math.random() * poolCopy.length);
                        const vid = poolCopy[randIdx];
                        videosToAdd.push(vid);
                        currentPlaylistDuration += (vid.duration || 300); // fallback duration
                        // poolCopy.splice(randIdx, 1); // Allow repeats? maybe yes, maybe no. Let's allow repeats for infinite duration.
                        safety++;
                    }

                    if (videosToAdd.length > 0) {
                        // Create Temp Playlist
                        const playlistName = `SmartGen ${rotation.id.slice(0, 4)}`;
                        const newPlaylist = await Playlist.create({
                            name: playlistName,
                            description: 'Auto-generated for Smart Rotation',
                            is_shuffle: 0,
                            user_id: userId,
                            youtube_channel_id: channelId
                        });

                        // Add videos to playlist
                        // Limitation: DB calls inside loop. Optimization: Batch insert if possible, but existing API is one-by-one.
                        // We'll limit max videos to avoid slow generation.
                        const maxVideos = 20; // Cap at 20 videos per rotation item to prevent huge delays
                        for (let pos = 0; pos < Math.min(videosToAdd.length, maxVideos); pos++) {
                            await Playlist.addVideo(newPlaylist.id, videosToAdd[pos].id, pos + 1);
                        }

                        targetId = `playlist:${newPlaylist.id}`;
                        targetTitle = videosToAdd[0].title;
                        contentThumbnailFallback = videosToAdd[0].thumbnail_path;
                    } else {
                        // Fallback simple
                        const vid = contentPool[Math.floor(Math.random() * contentPool.length)];
                        targetId = vid.id;
                        targetTitle = vid.title;
                        contentThumbnailFallback = vid.thumbnail_path;
                    }
                }

                if (displayTitle) {
                    targetTitle = displayTitle;
                }

                // Select Thumbnail Logic
                let selectedThumbnailPath = null;
                if (thumbnailMode === 'gallery' && galleryThumbnails.length > 0) {
                    selectedThumbnailPath = galleryThumbnails[Math.floor(Math.random() * galleryThumbnails.length)].filepath;
                } else if (thumbnailMode === 'video') {
                    selectedThumbnailPath = contentThumbnailFallback;
                } else {
                    // 'auto' mode: Gallery preferred, Video fallback
                    if (galleryThumbnails.length > 0) {
                        selectedThumbnailPath = galleryThumbnails[Math.floor(Math.random() * galleryThumbnails.length)].filepath;
                    } else {
                        selectedThumbnailPath = contentThumbnailFallback;
                    }
                }

                // Add Item to Rotation
                await Rotation.addItem({
                    rotation_id: rotation.id,
                    order_index: i,
                    video_id: targetId, // This is now 'playlist:UUID'
                    title: targetTitle,
                    description: targetDesc,
                    tags: 'smart-rotation',
                    privacy: privacy,
                    category: '10',
                    thumbnail_path: selectedThumbnailPath,
                    original_thumbnail_path: selectedThumbnailPath
                });

                generatedCount.push(rotation.id);
                nextStartTime = new Date(streamEndTime.getTime() + 5 * 60000); // 5 min gap
            }
        }

        return { success: true, count: generatedCount.length };
    }
}

module.exports = AutoSchedulerService;
