const Stream = require('../models/Stream');
const Playlist = require('../models/Playlist');
const Video = require('../models/Video');
const User = require('../models/User');
const Thumbnail = require('../models/Thumbnail');
const Rotation = require('../models/Rotation'); // Import Rotation model
const { v4: uuidv4 } = require('uuid');

class AutoSchedulerService {
    /**
     * Generates a random schedule for the given channel for N days.
     * @param {string} channelId - The YouTube Channel ID.
     * @param {string} userId - The owner's User ID.
     * @param {object} config - Configuration object.
     * @param {number} config.daysCount - Number of days to generate.
     * @param {number} config.minStreamsPerDay - Min streams per day.
     * @param {number} config.maxStreamsPerDay - Max streams per day.
     * @param {number} config.minDurationHours - Min duration per stream.
     * @param {number} config.maxDurationHours - Max duration per stream.
     * @param {string} config.contentType - 'video' or 'playlist'.
     * @param {string[]} config.customTitles - Array of custom titles to randomize.
     */
    static async generateRotationSchedule(channelId, userId, config) {
        // ... (Existing Stream Logic - kept for reference or legacy use) ...
        // For brevity in this edit, I will focus on adding the new method below.
        // But since I'm rewriting the file, I should include the existing method too.
        console.log('[AutoScheduler] Starting generation with config:', config);
        const {
            daysCount = 14,
            minStreamsPerDay = 6,
            maxStreamsPerDay = 12,
            minDurationHours = 3,
            maxDurationHours = 7,
            contentType = 'video',
            customTitles = []
        } = config;

        // 1. Fetch Content Pool
        let contentPool = [];
        if (contentType === 'playlist') {
            contentPool = await Playlist.findAll(userId, channelId);
            contentPool = contentPool.filter(p => p.video_count > 0);
            if (contentPool.length === 0) {
                throw new Error('No valid playlists found for this channel.');
            }
        } else {
            contentPool = await Video.findAll(userId, channelId);
            if (contentPool.length === 0) {
                throw new Error('No videos found for this channel.');
            }
        }

        // 2. Fetch Thumbnail Pool
        let allThumbnails = await Thumbnail.findAll(userId, null);
        const channelThumbnails = await Thumbnail.findAll(userId, channelId);
        allThumbnails = [...allThumbnails, ...channelThumbnails];
        allThumbnails = allThumbnails.filter((t, index, self) =>
            index === self.findIndex((t2) => (t2.id === t.id))
        );

        // 3. Generation Loop
        const generatedStreams = [];
        const now = new Date();
        let startDate = new Date(now);
        startDate.setDate(startDate.getDate() + 1);
        startDate.setHours(6, 0, 0, 0);

        for (let day = 0; day < daysCount; day++) {
            const currentDayStart = new Date(startDate);
            currentDayStart.setDate(startDate.getDate() + day);

            const streamsToday = Math.floor(Math.random() * (maxStreamsPerDay - minStreamsPerDay + 1)) + minStreamsPerDay;
            let nextStartTime = new Date(currentDayStart);

            for (let i = 0; i < streamsToday; i++) {
                const durationHours = (Math.random() * (maxDurationHours - minDurationHours) + minDurationHours);
                const durationSeconds = Math.floor(durationHours * 3600);
                const streamStartTime = new Date(nextStartTime);
                const streamEndTime = new Date(streamStartTime.getTime() + durationSeconds * 1000);

                let targetId = null;
                let streamTitle = '';
                let streamDescription = '';

                if (contentType === 'playlist') {
                    const playlist = contentPool[Math.floor(Math.random() * contentPool.length)];
                    targetId = playlist.id;
                    streamTitle = playlist.name;
                } else {
                    const videosToAdd = [];
                    let currentPlaylistDuration = 0;
                    let safety = 0;
                    while (currentPlaylistDuration < durationSeconds && safety < 1000) {
                        const vid = contentPool[Math.floor(Math.random() * contentPool.length)];
                        videosToAdd.push(vid);
                        currentPlaylistDuration += vid.duration;
                        safety++;
                    }
                    if (videosToAdd.length === 0) continue;
                    const playlistName = `SmartGen ${currentDayStart.toISOString().split('T')[0]} #${i + 1}`;
                    const newPlaylist = await Playlist.create({
                        name: playlistName,
                        description: 'Auto-generated by Smart Scheduler',
                        is_shuffle: 0,
                        user_id: userId,
                        youtube_channel_id: channelId
                    });
                    for (let pos = 0; pos < videosToAdd.length; pos++) {
                        await Playlist.addVideo(newPlaylist.id, videosToAdd[pos].id, pos + 1);
                    }
                    targetId = newPlaylist.id;
                    const randomVid = videosToAdd[Math.floor(Math.random() * videosToAdd.length)];
                    streamTitle = randomVid.title;
                    streamDescription = `Auto-generated stream featuring ${videosToAdd[0].title} and more.`;
                }

                if (customTitles && customTitles.length > 0) {
                    streamTitle = customTitles[Math.floor(Math.random() * customTitles.length)];
                }

                let selectedThumbnailPath = null;
                let selectedThumbnailId = null;
                if (allThumbnails.length > 0) {
                    const randThumb = allThumbnails[Math.floor(Math.random() * allThumbnails.length)];
                    selectedThumbnailId = randThumb.id;
                    selectedThumbnailPath = randThumb.filepath;
                }

                const streamData = {
                    title: streamTitle.substring(0, 100),
                    video_id: targetId,
                    schedule_time: streamStartTime.toISOString(),
                    end_time: streamEndTime.toISOString(),
                    duration: durationSeconds,
                    status: 'scheduled',
                    platform: 'YouTube',
                    platform_icon: 'brand-youtube',
                    loop_video: true,
                    use_advanced_settings: true,
                    user_id: userId,
                    youtube_channel_id: channelId,
                    youtube_description: streamDescription,
                    youtube_privacy: 'unlisted',
                    youtube_category: '10',
                    youtube_tags: 'auto-generated,smart-rotation',
                    youtube_thumbnail: selectedThumbnailPath,
                    thumbnail_id: selectedThumbnailId
                };

                await Stream.create(streamData);
                generatedStreams.push(streamData);
                nextStartTime = new Date(streamEndTime.getTime() + 5 * 60000);
            }
        }
        return { success: true, count: generatedStreams.length };
    }

    /**
     * Generates ROTATION records instead of Stream records.
     * This allows them to appear in the "Rotations" UI with full features.
     */
    static async generateRotations(channelId, userId, config) {
        console.log('[AutoScheduler] Starting ROTATION generation with config:', config);
        const {
            daysCount = 14,
            minStreamsPerDay = 5,
            maxStreamsPerDay = 10,
            contentType = 'video',
            customTitles = []
        } = config;

        // 1. Fetch Content Pool
        let contentPool = [];
        if (contentType === 'playlist') {
            contentPool = await Playlist.findAll(userId, channelId);
            contentPool = contentPool.filter(p => p.video_count > 0);
        } else {
            contentPool = await Video.findAll(userId, channelId);
        }

        if (contentPool.length === 0) {
            throw new Error(`No ${contentType}s found for this channel.`);
        }

        // 2. Fetch Thumbnail Pool
        let allThumbnails = await Thumbnail.findAll(userId, null);
        const channelThumbnails = await Thumbnail.findAll(userId, channelId);
        allThumbnails = [...allThumbnails, ...channelThumbnails];
        allThumbnails = allThumbnails.filter((t, index, self) =>
            index === self.findIndex((t2) => (t2.id === t.id))
        );

        // 3. Generation Loop
        const generatedCount = [];
        const now = new Date();
        let startDate = new Date(now);
        startDate.setDate(startDate.getDate()); // Start today/tomorrow? Let's start tomorrow to be safe or today if needed
        // Assuming starting tomorrow 06:00 like regular scheduler
        startDate.setDate(startDate.getDate() + 1);
        startDate.setHours(6, 0, 0, 0);

        for (let day = 0; day < daysCount; day++) {
            const currentDayStart = new Date(startDate);
            currentDayStart.setDate(startDate.getDate() + day);

            const streamsToday = Math.floor(Math.random() * (maxStreamsPerDay - minStreamsPerDay + 1)) + minStreamsPerDay;
            let nextStartTime = new Date(currentDayStart);

            for (let i = 0; i < streamsToday; i++) {
                // Fixed duration range for rotations (3-7 hours generally good)
                const durationHours = (Math.random() * (7 - 3) + 3);
                const durationSeconds = Math.floor(durationHours * 3600);

                const streamStartTime = new Date(nextStartTime);
                const streamEndTime = new Date(streamStartTime.getTime() + durationSeconds * 1000);

                // Prepare Title
                // Default: "Smart - Date Time" (user can rename later)
                // OR use Custom Title if provided
                let rotationName = `Smart - ${streamStartTime.toLocaleDateString('id-ID', { day: '2-digit', month: 'short' })} ${streamStartTime.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit', hour12: false })}`;

                let displayTitle = '';
                if (customTitles && customTitles.length > 0) {
                    displayTitle = customTitles[Math.floor(Math.random() * customTitles.length)];
                    // Also append to rotation name for detailed view?
                    // rotationName = `${displayTitle.substring(0, 20)}... (${streamStartTime.getDate()})`;
                }

                // Create Rotation Record
                const rotation = await Rotation.create({
                    user_id: userId,
                    name: rotationName,
                    youtube_channel_id: channelId,
                    start_time: streamStartTime.toISOString().replace('Z', ''),
                    end_time: streamEndTime.toISOString().replace('Z', ''),
                    repeat_mode: 'none', // Specific date schedule -> No repeat
                    status: 'active', // Set ACTIVE so it shows as ready/running
                    is_loop: true,
                    gap_minutes: 0
                });

                // Pick Content
                let targetId = ''; // playlist:ID or videoID
                let targetTitle = '';
                let targetDesc = '';

                if (contentType === 'playlist') {
                    const pl = contentPool[Math.floor(Math.random() * contentPool.length)];
                    targetId = `playlist:${pl.id}`;
                    targetTitle = pl.name;
                    targetDesc = pl.description || '';
                } else {
                    // Single Video Mode for Rotation (Rotation supports single items nicely)
                    // Or should we create a playlist?
                    // Rotations usually play items in sequence.
                    // If we want a "Block" of videos, we can add multiple items to the rotation?
                    // OR stick to the "Video Acak (Playlist Baru)" logic of creating a playlist FIRST.

                    // Logic: Create a playlist of videos, then add that playlist as a single item to Rotation
                    const videosToAdd = [];
                    let currentPlaylistDuration = 0;
                    let safety = 0;
                    while (currentPlaylistDuration < durationSeconds && safety < 100) {
                        const vid = contentPool[Math.floor(Math.random() * contentPool.length)];
                        videosToAdd.push(vid);
                        currentPlaylistDuration += vid.duration;
                        safety++;
                    }

                    if (videosToAdd.length > 0) {
                        const playlistName = `SmartGen ${currentDayStart.toISOString().split('T')[0]} #${i + 1}`;
                        const newPlaylist = await Playlist.create({
                            name: playlistName,
                            description: 'Auto-generated for Smart Rotation',
                            is_shuffle: 0,
                            user_id: userId,
                            youtube_channel_id: channelId
                        });
                        for (let pos = 0; pos < videosToAdd.length; pos++) {
                            await Playlist.addVideo(newPlaylist.id, videosToAdd[pos].id, pos + 1);
                        }
                        targetId = `playlist:${newPlaylist.id}`;
                        targetTitle = videosToAdd[0].title; // Title of first video as fallback
                    } else {
                        // Fallback to single random video if loop failed
                        const vid = contentPool[Math.floor(Math.random() * contentPool.length)];
                        targetId = vid.id;
                        targetTitle = vid.title;
                    }
                }

                // Override Item Title with Custom Title
                if (displayTitle) {
                    targetTitle = displayTitle;
                }

                // Select Thumbnail
                let selectedThumbnailPath = null;
                if (allThumbnails.length > 0) {
                    const randThumb = allThumbnails[Math.floor(Math.random() * allThumbnails.length)];
                    selectedThumbnailPath = randThumb.filepath;
                }

                // Add Item to Rotation
                await Rotation.addItem({
                    rotation_id: rotation.id,
                    order_index: 0,
                    video_id: targetId,
                    title: targetTitle,
                    description: targetDesc,
                    tags: 'smart-rotation',
                    privacy: 'public', // Default public? User asked for 24/7 radio usually public.
                    category: '10', // Music
                    thumbnail_path: selectedThumbnailPath,
                    original_thumbnail_path: selectedThumbnailPath
                });

                generatedCount.push(rotation.id);
                nextStartTime = new Date(streamEndTime.getTime() + 5 * 60000); // 5 min buffer
            }
        }

        return { success: true, count: generatedCount.length };
    }
}

module.exports = AutoSchedulerService;
